name: f_jzshop
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  carousel_slider: ^4.2.1
  dio: ^5.3.4
  dotted_border: ^2.1.0
  file_picker: ^6.1.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  pretty_dio_logger: ^1.3.1
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/iconGG.png
    - assets/images/iconFB.png
    - assets/images/logoJZ.png